--SUBQUERY 

--Bizden alýþveriþ yapan müþterilerin listesi


SELECT U.NAMESURNAME, COUNT(B.ID)
FROM USER_ U
JOIN BASKET B ON B.USERID=U.ID
GROUP BY U.NAMESURNAME

--Bu þekilde alýþveriþ yapmýþ müþterilermiz geldi.

--Þimdi tüm müþterilerimii getirelim yanlarýnda alýþveriþ yapýp yapmadýklarý yazsýn.

SELECT U.NAMESURNAME, COUNT(B.ID)
FROM USER_ U
LEFT JOIN BASKET B ON B.USERID=U.ID
GROUP BY U.NAMESURNAME

--Alýþ veriþ yapanlarýn yanlarýnd bilgi ile birlikte.


SELECT U.NAMESURNAME, COUNT(B.ID)
FROM USER_ U
LEFT JOIN BASKET B ON B.USERID=U.ID
GROUP BY U.NAMESURNAME 
HAVING COUNT(B.ID)>0


--Þimdi bunlarý SUBQUERY ile yapalým.

SELECT U.NAMESURNAME, 
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID)
FROM USER_ U

SELECT U.NAMESURNAME, 
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID)
FROM USER_ U
WHERE (SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID)>0


--SUBQUERY ÝLE MÜÞTERÝ BÝLGÝSÝ GETÝRME.

--En son sepete ekleme yaptýðý tarih.

SELECT ID, NAMESURNAME,
(SELECT MAX(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) LASTBASKETDATE
FROM USER_ U

--NULL gelenler daha önce hiç alýþveriþ yapmamaýþ olanlar.

--Kullanýcý kaç kere sepete ekleme yapmýþtýr. 0 dan büyük olanlar.

SELECT ID, NAMESURNAME,
(SELECT MAX(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) LASTBASKETDATE,
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID) BASKETCOUNT
FROM USER_ U
WHERE (SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID) > 0
ORDER BY 4 DESC


--Yukarýdakiler dahil ilk tarihi de getirelim.

SELECT ID, NAMESURNAME,
(SELECT MAX(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) LASTBASKETDATE,
(SELECT MIN(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) FIRSTBASKETDATE,
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID) BASKETCOUNT
FROM USER_ U
WHERE (SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID) > 0
ORDER BY 5 DESC

--Toplam harcamayý da getirelim.

SELECT ID, NAMESURNAME,
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID) BASKETCOUNT,
(SELECT MIN(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) FIRSTBASKETDATE,
(SELECT MAX(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) LASTBASKETDATE,
(SELECT SUM(TOTAL) FROM BASKETDETAIL WHERE BASKETID IN (SELECT ID FROM BASKET WHERE USERID=U.ID)) AS TOTAL
FROM USER_ U
WHERE (SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID)>0
ORDER BY 6 DESC


--Toplam kaç ürün aldýðýný da hesaplayalým.

SELECT ID, NAMESURNAME,
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID) BASKETCOUNT,
(SELECT MIN(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) FIRSTBASKETDATE,
(SELECT MAX(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) LASTBASKETDATE,
(SELECT SUM(TOTAL) FROM BASKETDETAIL WHERE BASKETID IN (SELECT ID FROM BASKET WHERE USERID=U.ID)) AS TOTAL,
(SELECT COUNT(*) FROM BASKETDETAIL WHERE BASKETID IN (SELECT ID FROM BASKET WHERE USERID=U.ID)) ITEMCOUNT
FROM USER_ U
WHERE (SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID)>0
ORDER BY 7 DESC


--Ayný sorgu iþlemini JOIN ile yapalým.

SELECT U.ID, U.NAMESURNAME, 
COUNT(B.ID) BASKETCOUNT, MIN(B.CREATEDDATE) FIRSTBASKETDATE,
MAX(B.CREATEDDATE) LASTBASKETDATE, SUM(BD.TOTAL) TOTAL, COUNT(BD.ID) ITEMCOUNT
FROM USER_ U
JOIN BASKET B ON B.USERID=U.ID
JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
GROUP BY U.ID, U.NAMESURNAME



/*
MÜÞTERÝNÝN SEPETÝNE EKLEDÝÐÝ SON ÜRÜN...

Normal JOIN iþlemleri ile bunun getirilebilmesi mümkün deðildir. 
JOIN iþlemleri ile ancak son ekleme tarihine gidilebilmektedir.

Bu sebepten dolayý SUBQUERY kullanýmý kaçýnýlmaz hale gelmektedir.
*/

SELECT ID, NAMESURNAME,
(SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID) BASKETCOUNT,
(SELECT MIN(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) FIRSTBASKETDATE,
(SELECT MAX(CREATEDDATE) FROM BASKET WHERE USERID=U.ID) LASTBASKETDATE,
(SELECT SUM(TOTAL) FROM BASKETDETAIL WHERE BASKETID IN (SELECT ID FROM BASKET WHERE USERID=U.ID)) AS TOTAL,
(SELECT COUNT(*) FROM BASKETDETAIL WHERE BASKETID IN (SELECT ID FROM BASKET WHERE USERID=U.ID)) ITEMCOUNT,
(
	SELECT ITEMNAME FROM ITEM WHERE ID IN 
		(
			SELECT TOP 1 ITEMID FROM BASKETDETAIL WHERE BASKETID IN 
				(
					SELECT ID FROM BASKET WHERE USERID=U.ID
				)ORDER BY DATE_ DESC
		)

) LASTITEMNAME

FROM USER_ U
WHERE (SELECT COUNT(*) FROM BASKET WHERE USERID=U.ID)>0



