--SATIÞ OLUÞTURDUKAN SONRA BURADAN SORGULUYORUZ

SELECT * FROM BASKET         --Sepette 1 ürün var userýd 1068 rastgele. Buna aþaðýda bakalým.
SELECT * FROM BASKETDETAIL   --Ne almýþ 
SELECT * FROM PAYMENT        --465,4 ödeme
SELECT * FROM ORDER_
SELECT * FROM ORDERDETAIL
SELECT * FROM INVOICE
SELECT * FROM INVOICEDETAIL

--Kim almýþ
SELECT * FROM USER_ WHERE ID=1068

SELECT U.NAMESURNAME, B.CREATEDDATE 
FROM USER_ U
JOIN BASKET B ON B.USERID=U.ID

--Sadece joýn kullanmamýzýn sebebi basket tablomuzda 1 satýr var 
--ve sadece bu müþterimzin bilgilerini getirmek istiyoruz.


SELECT U.NAMESURNAME, B.CREATEDDATE, BD.AMOUNT, BD.PRICE, BD.TOTAL, I.ITEMCODE,
I.ITEMNAME, I.CATEGORY1, I.CATEGORY2, I.CATEGORY3, A.ADDRESSTEXT, C.CITY, 
T.TOWN, D.DISTRICT, INV.INVOICENO, INV.CARGOFICHENO, INV.DATE_ SHIPDATE
FROM USER_ U
JOIN BASKET B ON B.USERID=U.ID
JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
JOIN ITEM I ON I.ID=BD.ID
JOIN ORDER_ O ON O.BASKETID=B.ID
JOIN ADDRES A ON A.ID=O.ADDRESSID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
JOIN INVOICE INV ON INV.ORDERID=O.ID


--Bir kullanýcýnýn yaptýðý alýþveriþ sayýsý, adedi ve tutarý.

SELECT U.NAMESURNAME ADSOYAD, COUNT(BD.ID) ALISVERISSAYISI, 
SUM(BD.AMOUNT) ALINANURUNSAYISI, SUM(TOTAL) TOPLAMTUTAR
FROM USER_ U
JOIN BASKET B ON B.USERID=U.ID
JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
JOIN ITEM I ON I.ID=BD.ID
JOIN ORDER_ O ON O.BASKETID=B.ID
JOIN ADDRES A ON A.ID=O.ADDRESSID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
JOIN INVOICE INV ON INV.ORDERID=O.ID
GROUP BY  U.NAMESURNAME

--Þimdi daha fazla satýþ oluþturup yukarýdaki kodu tekrar çalýþtýralým...


--Ayný bilgileri þehir kýrýlýmýnda getirelim.

SELECT C.CITY SEHIR, COUNT(BD.ID) ALISVERISSAYISI, 
SUM(BD.AMOUNT) ALINANURUNSAYISI, SUM(TOTAL) TOPLAMTUTAR
FROM USER_ U
JOIN BASKET B ON B.USERID=U.ID
JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
JOIN ITEM I ON I.ID=BD.ID
JOIN ORDER_ O ON O.BASKETID=B.ID
JOIN ADDRES A ON A.ID=O.ADDRESSID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
JOIN INVOICE INV ON INV.ORDERID=O.ID
GROUP BY  C.CITY