--- ÖRNEK 2 ---

--EN ÇOK SATIÞ YAPILAN MÜÞERÝLER.

SELECT U.NAMESURNAME ADSOYAD, COUNT(BD.ID) ALISVERISSAYISI, 
SUM(BD.AMOUNT) URUNSAYISI, SUM(TOTAL) TOPLAMTUTAR
FROM USER_ U
JOIN BASKET B ON B.USERID=U.ID
JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
JOIN ORDER_ O ON O.BASKETID=B.ID
JOIN ADDRES A ON A.ID=O.ADDRESSID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
JOIN INVOICE INV ON INV.ORDERID=O.ID
GROUP BY  U.NAMESURNAME 
ORDER BY SUM(TOTAL) DESC


--Þatýþ sayýmýzý 1000 e çýkartalým.
--Satýþ oluþturma tablosu ile...

--1000 Satýþa çýkarýldý.

--Yani durumda en çok satý yapan 10 müþteri.

SELECT TOP 10 U.NAMESURNAME ADSOYAD, COUNT(BD.ID) ALISVERISSAYISI, 
SUM(BD.AMOUNT) URUNSAYISI, SUM(TOTAL) TOPLAMTUTAR
FROM USER_ U
JOIN BASKET B ON B.USERID=U.ID
JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
JOIN ORDER_ O ON O.BASKETID=B.ID
JOIN ADDRES A ON A.ID=O.ADDRESSID
JOIN CITY C ON C.ID=A.CITYID
JOIN TOWN T ON T.ID=A.TOWNID
JOIN DISTRICT D ON D.ID=A.DISTRICTID
JOIN INVOICE INV ON INV.ORDERID=O.ID
GROUP BY  U.NAMESURNAME 
ORDER BY SUM(TOTAL) DESC





--- ÖRNEK 3 ---

--EN ÇOK SATIÞ YAPILAN ÜRÜN KATEGORÝLERÝ.

SELECT I.CATEGORY1, SUM(OD.TOTALPRICE) TOPLAMTUTAR
FROM ITEM I
JOIN ORDERDETAIL OD ON OD.ITEMID=I.ID
JOIN ORDER_ O ON O.ID=OD.ORDERID
GROUP BY I.CATEGORY1
ORDER BY 2 DESC

--CATEGORY1 de bulunan "elektronik-gida-disi" nýn CATEGORY2 de bulunan alt 
--ürünlerine bir bakalým ve bunlarý sýralayalým.

SELECT I.CATEGORY1, I.CATEGORY2, SUM(OD.TOTALPRICE) TOTAL
FROM ITEM I
JOIN ORDERDETAIL OD ON OD.ITEMID=I.ID
JOIN ORDER_ O ON O.ID=OD.ORDERID
WHERE I.CATEGORY1 = 'elektronik-gida-disi'
GROUP BY I.CATEGORY1, I.CATEGORY2
ORDER BY 3 DESC 




--- ÖRNEK 3 ---

--OCAK 2018 (2021) DE BÝZDEN ALIÞVERÝÞ YAPAN KADIN VE ERKEK MÜÞTERÝLER

SELECT U.GENDER, SUM(BD.TOTAL) TOTAL
FROM USER_ U
JOIN BASKET B ON B.USERID=U.ID
JOIN BASKETDETAIL BD ON BD.BASKETID=B.ID
WHERE B.CREATEDDATE BETWEEN '20210101' AND '20210131'
GROUP BY U.GENDER